// Code generated by "enumer -type=RscpError -json"; DO NOT EDIT.

//
package rscp

import (
	"encoding/json"
	"fmt"
)

const _RscpErrorName = "ERR_NOT_HANDLEDERR_ACCESS_DENIEDERR_FORMATERR_AGAINERR_OUT_OF_BOUNDSERR_NOT_AVAILABLEERR_UNKNOWN_TAGERR_ALREADY_IN_USE"

var _RscpErrorIndex = [...]uint8{0, 15, 32, 42, 51, 68, 85, 100, 118}

func (i RscpError) String() string {
	i -= 1
	if i >= RscpError(len(_RscpErrorIndex)-1) {
		return fmt.Sprintf("RscpError(%d)", i+1)
	}
	return _RscpErrorName[_RscpErrorIndex[i]:_RscpErrorIndex[i+1]]
}

var _RscpErrorValues = []RscpError{1, 2, 3, 4, 5, 6, 7, 8}

var _RscpErrorNameToValueMap = map[string]RscpError{
	_RscpErrorName[0:15]:    1,
	_RscpErrorName[15:32]:   2,
	_RscpErrorName[32:42]:   3,
	_RscpErrorName[42:51]:   4,
	_RscpErrorName[51:68]:   5,
	_RscpErrorName[68:85]:   6,
	_RscpErrorName[85:100]:  7,
	_RscpErrorName[100:118]: 8,
}

// RscpErrorString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func RscpErrorString(s string) (RscpError, error) {
	if val, ok := _RscpErrorNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to RscpError values", s)
}

// RscpErrorValues returns all values of the enum
func RscpErrorValues() []RscpError {
	return _RscpErrorValues
}

// IsARscpError returns "true" if the value is listed in the enum definition. "false" otherwise
func (i RscpError) IsARscpError() bool {
	for _, v := range _RscpErrorValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for RscpError
func (i RscpError) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for RscpError
func (i *RscpError) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("RscpError should be a string, got %s", data)
	}

	var err error
	*i, err = RscpErrorString(s)
	return err
}
